### ISSUE TITLE
How to compile this project with lv_micropython

### ISSUE THREAD

**Issue by venusmariga** [russhughes/s3lcd#15]
This is a great project, I completed the firmware compilation using esp-idf v4.4.6 version in wt32-sc01-plus. But the compilation project I used was lv_micropython, and there was no lvgl module in the final compiled firmware. How do I achieve the joint compilation of lv_micropython and s3lcd?
I want to use lvgl in wt32-sc01-plus with micropython

**Comment by russhughes** [comment]
lvgl is not compatible with this driver.
