### ISSUE TITLE
Which firmware image should be used for the T-Display-S3 board?

### ISSUE THREAD

**Issue by kf106** [russhughes/s3lcd#16]
And if there's a functioning bootloader, can the image just be loaded at 0x1000?

**Comment by russhughes** [comment]
Use the firmware from the [S3LCD_OCT_16M](https://github.com/russhughes/s3lcd/tree/main/firmware#s3lcd_oct_16m-octal-spiram-16m-flash) folder. The image must be loaded at 0x0.

**Comment by kf106** [comment]
Thank you! That worked and I now have a Python REPL that I can talk to through screen.

If I write a micropython.py program do I need to build my own firmware, or can I upload it somehow to the device so it's permanently there?

**Comment by russhughes** [comment]
You can upload py files (or mpy files compiled with mpy-cross) to your device's flash filesystem using one of several utilities like mpremote or thonny.

**Comment by crbn60** [comment]
I'm just trying to get off the struggle bus with zero MPY knowledge. I flashed the firmware file and have a REPL I can interact with as well as run code on the board using pyboard. I don't have a `tft_config` module, where does that come from?

I would like to start by just running the example code.

**Comment by russhughes** [comment]
@crbn60 You need to upload one of the tft_config.py (and for a few examples, tft_buttons.py) modules for you device from the examples/config folder.

**Comment by crbn60** [comment]
Thank you very much for taking the time @russhughes , I'm up and running.

**Comment by russhughes** [comment]
@crbn60 You're wecome, enjoy.
