### ISSUE TITLE
ImportError: no module named 'tft_config' on Lilygo T-Display-S3

### ISSUE THREAD

**Issue by achtnullzwei** [russhughes/s3lcd#21]
First of all, thx a lot for providing pre-compiled firmware :-)

I flashed the firmware.bin from [ESP32_GENERIC_S3_SPIRAM_OCT_16MiB](https://github.com/russhughes/s3lcd/tree/main/firmware/ESP32_GENERIC_S3_SPIRAM_OCT_16MiB) as that is suggested for T-Display S3 in your readme.

However, when I try to load e.g. hello.py from the examples folder i get the following error. Not sure if i am doing something wrong but it cannot import the tft_config module.

Thx a lot in advance.

**Comment by achtnullzwei** [comment]
Sry. Found it in the config folder.

**Comment by russhughes** [comment]
Use the tft_config.py and tft_buttons.py config modules in [examples/configs/t-display-s3.](https://github.com/russhughes/s3lcd/tree/main/examples/configs/t-display-s3)

**Comment by achtnullzwei** [comment]
I found it literally a minute before your comment. Anyway thx for the quick response. Should have had a closer look before opening an issue ;-)
