### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by GitterBug777** [russhughes/s3lcd#23]
Where is tft_config.py?  In particular for TDongle S3 and t-QT Pro.

**Comment by foopod** [comment]
They are in `examples/config/` folder of the repo.

[t-qt-pro](https://github.com/russhughes/s3lcd/blob/main/examples/configs/t-qt-pro/tft_config.py)
[t-dongle-s3](https://github.com/russhughes/s3lcd/blob/main/examples/configs/t-dongle-s3/tft_config.py)
