### ISSUE TITLE
Getting error when compile the fimrware with IDF 4.4.6 and micropython v1.20.0

### ISSUE THREAD

**Issue by amplatzer** [russhughes/s3lcd#27]
/s3lcd.c.obj -c /s3lcd/src/s3lcd.c
/s3lcd/src/s3lcd.c: In function 's3lcd_idle_mode':
/s3lcd/src/s3lcd.c:388:52: error: 'ST7796_IDLEOFF' undeclared (first use in this function); did you mean 'ST7789_IDLEOFF'?
         esp_lcd_panel_io_tx_param(self->io_handle, ST7796_IDLEOFF, NULL, 0);
                                                    ^~~~~~~~~~~~~~
                                                    ST7789_IDLEOFF
/s3lcd/src/s3lcd.c:388:52: note: each undeclared identifier is reported only once for each function it appears in
ninja: build stopped: subcommand failed.
ninja failed with exit code 1

**Comment by russhughes** [comment]
Yep, that’s a bug alright.
