### ISSUE TITLE
Feature Request: LVGL integration

### ISSUE THREAD

**Issue by coolbikerdad** [russhughes/s3lcd#7]
Hi Russ.
Thanks so much for your work on display drivers for the ESP32 boards to date, and providing ready-to-go firmware images. You're a star.
Have you considered adding support for LVGL into your builds? It would add an extra dimension and I'm sure I'm not the only one that would really appreciate a strong graphics library to complement your driver. Sadly, I'm too near the start of my Micropython journey to be attempt this myself.
Best
Neil

**Comment by russhughes** [comment]
I'm not planning LGVL integration for this driver as I did for [st7789 and st7735 Support](https://github.com/lvgl/lv_binding_micropython/commit/6e0cc0f9c1e58c4a41e551172c83272b56571c33) hybrid driver.
